# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'appBkp.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1199, 892)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.topShowList = QtWidgets.QLabel(self.centralwidget)
        self.topShowList.setGeometry(QtCore.QRect(20, 240, 181, 41))
        self.topShowList.setObjectName("topShowList")
        self.titulo = QtWidgets.QLabel(self.centralwidget)
        self.titulo.setGeometry(QtCore.QRect(10, 20, 431, 51))
        font = QtGui.QFont()
        font.setItalic(True)
        self.titulo.setFont(font)
        self.titulo.setObjectName("titulo")
        self.showList = QtWidgets.QListWidget(self.centralwidget)
        self.showList.setGeometry(QtCore.QRect(20, 290, 261, 391))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.showList.setFont(font)
        self.showList.setObjectName("showList")
        self.musicList = QtWidgets.QListWidget(self.centralwidget)
        self.musicList.setGeometry(QtCore.QRect(310, 290, 261, 391))
        self.musicList.setObjectName("musicList")
        self.showBtn = QtWidgets.QPushButton(self.centralwidget)
        self.showBtn.setGeometry(QtCore.QRect(150, 770, 131, 111))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.showBtn.setFont(font)
        self.showBtn.setObjectName("showBtn")
        self.imgShow = QtWidgets.QLabel(self.centralwidget)
        self.imgShow.setGeometry(QtCore.QRect(20, 90, 261, 141))
        self.imgShow.setText("")
        self.imgShow.setPixmap(QtGui.QPixmap("../../../../../../../home/nataniel/Desktop/Show.png"))
        self.imgShow.setScaledContents(True)
        self.imgShow.setObjectName("imgShow")
        self.imgPlace = QtWidgets.QLabel(self.centralwidget)
        self.imgPlace.setGeometry(QtCore.QRect(600, 90, 261, 141))
        self.imgPlace.setText("")
        self.imgPlace.setPixmap(QtGui.QPixmap("../../../../../../../home/nataniel/Desktop/Places.png"))
        self.imgPlace.setScaledContents(True)
        self.imgPlace.setObjectName("imgPlace")
        self.imgMusic = QtWidgets.QLabel(self.centralwidget)
        self.imgMusic.setGeometry(QtCore.QRect(310, 90, 261, 141))
        self.imgMusic.setText("")
        self.imgMusic.setPixmap(QtGui.QPixmap("../../../../../../../home/nataniel/Desktop/Discos.png"))
        self.imgMusic.setScaledContents(True)
        self.imgMusic.setObjectName("imgMusic")
        self.imgMovie = QtWidgets.QLabel(self.centralwidget)
        self.imgMovie.setGeometry(QtCore.QRect(890, 90, 261, 141))
        self.imgMovie.setText("")
        self.imgMovie.setPixmap(QtGui.QPixmap("../../../../../../../home/nataniel/Desktop/Movies.png"))
        self.imgMovie.setScaledContents(True)
        self.imgMovie.setObjectName("imgMovie")
        self.topDiscoList = QtWidgets.QLabel(self.centralwidget)
        self.topDiscoList.setGeometry(QtCore.QRect(310, 240, 271, 41))
        self.topDiscoList.setObjectName("topDiscoList")
        self.topPlaceList = QtWidgets.QLabel(self.centralwidget)
        self.topPlaceList.setGeometry(QtCore.QRect(600, 240, 261, 41))
        self.topPlaceList.setObjectName("topPlaceList")
        self.topMovieList = QtWidgets.QLabel(self.centralwidget)
        self.topMovieList.setGeometry(QtCore.QRect(890, 240, 271, 41))
        self.topMovieList.setObjectName("topMovieList")
        self.placeList = QtWidgets.QListWidget(self.centralwidget)
        self.placeList.setGeometry(QtCore.QRect(600, 290, 261, 391))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.placeList.setFont(font)
        self.placeList.setObjectName("placeList")
        self.movieList = QtWidgets.QListWidget(self.centralwidget)
        self.movieList.setGeometry(QtCore.QRect(890, 290, 261, 391))
        self.movieList.setObjectName("movieList")
        self.showRdAdd = QtWidgets.QRadioButton(self.centralwidget)
        self.showRdAdd.setGeometry(QtCore.QRect(20, 770, 121, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.showRdAdd.setFont(font)
        self.showRdAdd.setObjectName("showRdAdd")
        self.showRdRemove = QtWidgets.QRadioButton(self.centralwidget)
        self.showRdRemove.setGeometry(QtCore.QRect(20, 800, 96, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.showRdRemove.setFont(font)
        self.showRdRemove.setObjectName("showRdRemove")
        self.showRdSearch = QtWidgets.QRadioButton(self.centralwidget)
        self.showRdSearch.setGeometry(QtCore.QRect(20, 830, 96, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.showRdSearch.setFont(font)
        self.showRdSearch.setObjectName("showRdSearch")
        self.showInput = QtWidgets.QLineEdit(self.centralwidget)
        self.showInput.setGeometry(QtCore.QRect(20, 730, 261, 25))
        self.showInput.setObjectName("showInput")
        self.topAddShow = QtWidgets.QLabel(self.centralwidget)
        self.topAddShow.setGeometry(QtCore.QRect(20, 690, 181, 41))
        self.topAddShow.setObjectName("topAddShow")
        self.musicRdSearch = QtWidgets.QRadioButton(self.centralwidget)
        self.musicRdSearch.setGeometry(QtCore.QRect(318, 830, 96, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.musicRdSearch.setFont(font)
        self.musicRdSearch.setObjectName("musicRdSearch")
        self.musicBtn = QtWidgets.QPushButton(self.centralwidget)
        self.musicBtn.setGeometry(QtCore.QRect(448, 770, 121, 111))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.musicBtn.setFont(font)
        self.musicBtn.setObjectName("musicBtn")
        self.musicRdAdd = QtWidgets.QRadioButton(self.centralwidget)
        self.musicRdAdd.setGeometry(QtCore.QRect(318, 770, 121, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.musicRdAdd.setFont(font)
        self.musicRdAdd.setObjectName("musicRdAdd")
        self.musicInput = QtWidgets.QLineEdit(self.centralwidget)
        self.musicInput.setGeometry(QtCore.QRect(318, 730, 251, 25))
        self.musicInput.setObjectName("musicInput")
        self.topAddMusic = QtWidgets.QLabel(self.centralwidget)
        self.topAddMusic.setGeometry(QtCore.QRect(318, 690, 181, 41))
        self.topAddMusic.setObjectName("topAddMusic")
        self.musicRdRemove = QtWidgets.QRadioButton(self.centralwidget)
        self.musicRdRemove.setGeometry(QtCore.QRect(318, 800, 96, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.musicRdRemove.setFont(font)
        self.musicRdRemove.setObjectName("musicRdRemove")
        self.movieRdRemove = QtWidgets.QRadioButton(self.centralwidget)
        self.movieRdRemove.setGeometry(QtCore.QRect(890, 800, 96, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.movieRdRemove.setFont(font)
        self.movieRdRemove.setObjectName("movieRdRemove")
        self.movieRdSearch = QtWidgets.QRadioButton(self.centralwidget)
        self.movieRdSearch.setGeometry(QtCore.QRect(890, 830, 96, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.movieRdSearch.setFont(font)
        self.movieRdSearch.setObjectName("movieRdSearch")
        self.movieBtn = QtWidgets.QPushButton(self.centralwidget)
        self.movieBtn.setGeometry(QtCore.QRect(1020, 770, 121, 111))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.movieBtn.setFont(font)
        self.movieBtn.setObjectName("movieBtn")
        self.movieRdAdd = QtWidgets.QRadioButton(self.centralwidget)
        self.movieRdAdd.setGeometry(QtCore.QRect(890, 770, 121, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.movieRdAdd.setFont(font)
        self.movieRdAdd.setObjectName("movieRdAdd")
        self.movieInput = QtWidgets.QLineEdit(self.centralwidget)
        self.movieInput.setGeometry(QtCore.QRect(890, 730, 251, 25))
        self.movieInput.setObjectName("movieInput")
        self.topAddMovie = QtWidgets.QLabel(self.centralwidget)
        self.topAddMovie.setGeometry(QtCore.QRect(890, 690, 181, 41))
        self.topAddMovie.setObjectName("topAddMovie")
        self.placeRdSearch = QtWidgets.QRadioButton(self.centralwidget)
        self.placeRdSearch.setGeometry(QtCore.QRect(598, 830, 96, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.placeRdSearch.setFont(font)
        self.placeRdSearch.setObjectName("placeRdSearch")
        self.placeBtn = QtWidgets.QPushButton(self.centralwidget)
        self.placeBtn.setGeometry(QtCore.QRect(728, 770, 131, 111))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.placeBtn.setFont(font)
        self.placeBtn.setObjectName("placeBtn")
        self.placeRdAdd = QtWidgets.QRadioButton(self.centralwidget)
        self.placeRdAdd.setGeometry(QtCore.QRect(598, 770, 121, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.placeRdAdd.setFont(font)
        self.placeRdAdd.setObjectName("placeRdAdd")
        self.placeInput = QtWidgets.QLineEdit(self.centralwidget)
        self.placeInput.setGeometry(QtCore.QRect(598, 730, 261, 25))
        self.placeInput.setObjectName("placeInput")
        self.topAddPlace = QtWidgets.QLabel(self.centralwidget)
        self.topAddPlace.setGeometry(QtCore.QRect(598, 690, 181, 41))
        self.topAddPlace.setObjectName("topAddPlace")
        self.placeRdRemove = QtWidgets.QRadioButton(self.centralwidget)
        self.placeRdRemove.setGeometry(QtCore.QRect(598, 800, 96, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.placeRdRemove.setFont(font)
        self.placeRdRemove.setObjectName("placeRdRemove")
        self.showRdReset = QtWidgets.QRadioButton(self.centralwidget)
        self.showRdReset.setGeometry(QtCore.QRect(20, 860, 141, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.showRdReset.setFont(font)
        self.showRdReset.setObjectName("showRdReset")
        self.musicRdReset = QtWidgets.QRadioButton(self.centralwidget)
        self.musicRdReset.setGeometry(QtCore.QRect(320, 860, 141, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.musicRdReset.setFont(font)
        self.musicRdReset.setObjectName("musicRdReset")
        self.placeRdReset = QtWidgets.QRadioButton(self.centralwidget)
        self.placeRdReset.setGeometry(QtCore.QRect(600, 860, 141, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.placeRdReset.setFont(font)
        self.placeRdReset.setObjectName("placeRdReset")
        self.movieRdReset = QtWidgets.QRadioButton(self.centralwidget)
        self.movieRdReset.setGeometry(QtCore.QRect(890, 860, 141, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.movieRdReset.setFont(font)
        self.movieRdReset.setObjectName("movieRdReset")
        self.showListBkp = QtWidgets.QListWidget(self.centralwidget)
        self.showListBkp.setGeometry(QtCore.QRect(90, 690, 51, 31))
        self.showListBkp.setObjectName("showListBkp")
        self.musicListBkp = QtWidgets.QListWidget(self.centralwidget)
        self.musicListBkp.setGeometry(QtCore.QRect(490, 690, 51, 31))
        self.musicListBkp.setObjectName("musicListBkp")
        self.placeListBkp = QtWidgets.QListWidget(self.centralwidget)
        self.placeListBkp.setGeometry(QtCore.QRect(670, 690, 51, 31))
        self.placeListBkp.setObjectName("placeListBkp")
        self.movieListBkp = QtWidgets.QListWidget(self.centralwidget)
        self.movieListBkp.setGeometry(QtCore.QRect(1090, 690, 51, 31))
        self.movieListBkp.setObjectName("movieListBkp")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.topShowList.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">Shows que ja vi:</span></p></body></html>"))
        self.titulo.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt; font-weight:600;\">MMB - MY MEMORY BKP</span></p></body></html>"))
        self.showBtn.setText(_translate("MainWindow", "Bis?"))
        self.topDiscoList.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">Discos pra nao esquecer:</span></p></body></html>"))
        self.topPlaceList.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">Ja fui e volto:</span></p></body></html>"))
        self.topMovieList.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">Filmes/Series do S2:</span></p></body></html>"))
        self.showRdAdd.setText(_translate("MainWindow", "Acrescentar"))
        self.showRdRemove.setText(_translate("MainWindow", "Remover"))
        self.showRdSearch.setText(_translate("MainWindow", "Buscar"))
        self.topAddShow.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">Show:</span></p></body></html>"))
        self.musicRdSearch.setText(_translate("MainWindow", "Buscar"))
        self.musicBtn.setText(_translate("MainWindow", "Repeat?"))
        self.musicRdAdd.setText(_translate("MainWindow", "Acrescentar"))
        self.topAddMusic.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">Disco:</span></p></body></html>"))
        self.musicRdRemove.setText(_translate("MainWindow", "Remover"))
        self.movieRdRemove.setText(_translate("MainWindow", "Remover"))
        self.movieRdSearch.setText(_translate("MainWindow", "Buscar"))
        self.movieBtn.setText(_translate("MainWindow", "Açao?"))
        self.movieRdAdd.setText(_translate("MainWindow", "Acrescentar"))
        self.topAddMovie.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">Filme:</span></p></body></html>"))
        self.placeRdSearch.setText(_translate("MainWindow", "Buscar"))
        self.placeBtn.setText(_translate("MainWindow", "Vamos?"))
        self.placeRdAdd.setText(_translate("MainWindow", "Acrescentar"))
        self.topAddPlace.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">Lugar:</span></p></body></html>"))
        self.placeRdRemove.setText(_translate("MainWindow", "Remover"))
        self.showRdReset.setText(_translate("MainWindow", "Limpar tudo"))
        self.musicRdReset.setText(_translate("MainWindow", "Limpar tudo"))
        self.placeRdReset.setText(_translate("MainWindow", "Limpar tudo"))
        self.movieRdReset.setText(_translate("MainWindow", "Limpar tudo"))
